### ISSUE TITLE
Release 0.3.2

### ISSUE THREAD

**Issue by khiav223577** [haopingfan/quick_random_records#5]
It seems `0.3.2` is not released yet.
https://github.com/haopingfan/quick_random_records/blob/d492d317385d8d5fc884915e4dcfcc1275268586/lib/quick_random_records/version.rb#L2

**Comment by mashedkeyboard** [comment]
Getting annoying deprecation errors in my test logs at the moment because of this - @haopingfan, could you update the gem on rubygems.org? Thanks :)

**Comment by haopingfan** [comment]
@khiav223577 , @mashedkeyboard 

version `0.3.2` has just been released on rubygems.org.
Thanks for your feedback :D
